
title: Zeyang Ma's Website
page-top-title: Zeyang Ma
top-section-bg-text:
home-subtitle: Zeyang Ma&ensp;|&ensp;马泽洋
copyright-text: '&copy; Zeyang Ma 2026. All Rights Reserved.'
timezone: "America/Toronto"
